Repository teksi/district_heating, pull requests merged in 2025-01, with the labels that each got.

#71 upgrade ubuntu for CI
  .github/workflows/datamodel-create-dumps.yml
  .github/workflows/datamodel-test.yml
  .github/workflows/docs-builder.yml
  .github/workflows/plugin-package.yml
  .github/workflows/plugin-test.yml
  .github/workflows/project-translation.yml
Labels: CI/CD, sustainability

#72 Ajout des rubriques documents dans le projet QGIS
  project/teksi_district_heating.qgs
Labels: project

#80 2025-01-24-Adapt-and-update-trigger-and-functions
  datamodel/app/create_app.py
  datamodel/app/functions/modification_functions.sql
  datamodel/app/functions/oid_functions.sql
  datamodel/app/functions/organisation_functions.sql
  datamodel/changelogs/0001/14_default_values.sql
  datamodel/scripts/setup.sh
Labels: enhancement

#79 2025-01-24-add_vw_tdh_pipe_point
  datamodel/app/create_app.py
  datamodel/app/functions/meta_functions.sql
  datamodel/app/view/vw_tdh_pipe_point.py
Labels: enhancement
