Repository teksi/district_heating, pull requests merged in 2025-03, with the labels that each got.

#82 Add dictionnaries for files classname and datamedia
  datamodel/changelogs/0001/04_tdh_db_data_media_file.sql
  datamodel/changelogs/0001/09_tdh_data_media_file_dictionaries.sql
  datamodel/scripts/setup.sh
Labels: enhancement

#84 2025-02-04-add-trench_type_etc_to_pipe_section
  datamodel/changelogs/0001/05_tdh_db_pipe_section_extra_attributes.sql
  datamodel/changelogs/0001/09_tdh_db_pipe_section_extra_attributes_dictionaries.sql
  datamodel/scripts/setup.sh
Labels: enhancement, datamodel

#96 2025-03-24-adapt-vw_pipe_point_to_3D
  datamodel/app/view/vw_tdh_pipe_point.py
Labels: fix, feature
